// <auto-generated />
namespace KouTrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addworkerzip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addworkerzip));
        
        string IMigrationMetadata.Id
        {
            get { return "201703092320293_add workerzip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
