// <auto-generated />
namespace KouTrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class respell : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(respell));
        
        string IMigrationMetadata.Id
        {
            get { return "201703092341038_re-spell"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
